### ISSUE TITLE
Vírus???

### ISSUE THREAD

**Issue by Rencer** [szpeter80/hufilter#1]
Nem olyan rég az Adbolck-hoz bejelentettem egy bug-ot.
A próbléma az, hogy a Firefoxban amiben be van állítva, hogy elmentse és visszaállítsa az előző munkamenetet, amikor újrraindítom és egy Youtube oldal volt előzőleg megnyitva, akkor ebben az esetben nincsenek a reklámok szűrve. Ha reload-olom az oldalt akkor viszont eltűntek.
Most visszamentem az adblock bug-report oldalra és ott azt látom a "status" mezőben, hogy "hufilter - szerintem vírusod van"
Ez az az oldal : 
https://reports.adblockplus.org/f562d428-9d19-46d5-bbe3-cd8a82ea0483
Ez most akkor mi? Milyen vírusom van? Miből gondolod hogy az van?
Egyébként soha nem néztem vissza amikor bug-reportot küldtem az Adblock-ról, nem is tudom most miért mentettem el könyvjelzőbe. Egyébként ez a hiba random hol előjön hol nem, szóval amikor ujraindítom a FF-et egy Youtube oldallal ki vannnak szűrve a reklámok, de néha van hogy nem, aztán később megint jól működik nincsenek reklámok. Egyszerűen nem értem miért.
Az utóbbi időben nem volt ez a hiba, persze azóta FF is meg minden más frissült a gépemen talán több alkalommmal is.
Amúgy ez a vírus dolog azért is furcsa, mivel Linuxot használok, és ugye úgy tartja a mondás oda nem másznak be a vírusok. Bár ettől függetlenül szoktam Clamav-al időnként átnézni a gélpem, de az SOHA sem talált eddig semmit. Hálistennek...
Biztos nem az Adblock-kal vagy a valamelyik filterrel van (volt) a probléma?

**Comment by szpeter80** [comment]
Szia Rencer,

köszi a bejelentést. A bejelentés az ABP szűrőlista karbantartóihoz megy ki, szerintem a plugin írók nem nézik ezeket.

A hufilter átköltözött a hufilter/ org alá, ez a repo egy rövid grace időszak után törölve lesz, csak azért van itt, hogy a kliensek le tudják frissíteni a szűrő url-t.

Az ABP bejelentőjébe elég sok random bejelentés érkezik, aminek semmi köze se az ABP-hez, se a hufilterhez. A fenti bejelentésedben kb 10x annyi hasznos infó van, mint amennyit az ABP issue-ban megadtál, a sok NAGY BETŰ PEDIG OLYAN MINTHA ORDÍTANÁL. 

A vírusra visszatérve: valószínűleg nincs vírusod, bár a linux sem immunis rá. 

AZ ABP+hufilter+linux páros szokott működni, én is így használom. Annyi módosítással, hogy én megtiltom a FF-nek hogy history-t tároljon, és a lapokat/session se menti (csak ha összeomlik).  

Az általad leírt problémát (restore-olt sessionnál csak reload-ra aktív a szűrés) nem tudom mi okozza, az hogy véletlenszerűen jön elő, eléggé lekorlátozza a hibakeresés sikerét. Az ABP plugin fejlesztését nem követem, a hufilter nem szűri a YT-ot. 

Szerintem linux/ff/abp plugin probléma lehet, a szűrőlista egy fix állomány ami nem változik az oldal újratöltésére.

**Comment by Rencer** [comment]
Köszi a választ.

A nagybetűk soha az életben nem jelentettek ordítást.
Amióta világ a világ, írott szövegben a nagybetűket használják KIEMELÉSRE. (Nézz meg bármilyen hivatalos okmányt...) Szóval ne keverjük már bele az internetes agyhalot tizenéves trollok által kitalált elmebetegséget, egy HIVATALOS HIBABEJELENTŐ szövegben található szakszerűen, a legfontosabb ADATOKAT KEMELŐ írásmóddal. De minegy, leperegnek rólam az internetes baromságok...

Sajnos tényleg véletlenszerűen adódik ezt a probléma, és mint írtam egy jó ideje nem volt ilyen gond. Arra is gondolok, talán valamelyik Firefox verzióval voltak csak a gondok, bár ezt elég nehéz ellenőrizni, mivel sokszor pár naponta kap frissítést a FF.

**Comment by szpeter80** [comment]
Szia,

a netikett szerint a nagybetű kiabálást jelent, ez így van amióta a net létezik. Nem én találtam ki, de egyetértek vele, én ebben a kultúrában nőttem fel (rossz nyelvek szerint ez a folyamat a mai napig nem fejeződött be :) ). 

Erre gondolok:
https://tudasbazis.sulinet.hu/hu/informatika/informatika/informatika-4-evfolyam/a-halozat-hasznalatanak-alapszabalyai-a-netikett/netikett

A hufilternek nincs "hivatalos" bejelentője a szó polgári jogi / szerződéstechnikai értelmében, van pár editbox amibe lehet gépelni... és ennyi. Ez egy közösségi projekt amit magánemberek önszorgalomból csinálnak, ha és amennyire kedvük van hozzá, itt nyilván nem játszik a hivatalos okiratokban vett (szöveg)környezet.

A problémára visszatérve, remélem nem jön elő többet; az elmúlt hónapban én is láttam párszor "csuklani" a Firefox-ot,  most úgy tűnik elmúlt.

**Comment by Rencer** [comment]
Hát, minő csoda, épp most ahogy elindítom a FF-et és mit látok?
Ezt: http://keptarhely.eu/view.php?file=20190430v00ptpb0p.png
Jobb oldalt fent ott van egy reklám, és a videónál is látni, a tekerősávban, hogy ott vannak a kis sárga csíkocskák, ahol a reklámokat játsza be. Amikor rendesen szűrve van az oldal azok sem szoktak látszódni.
Ezeket a szűrőket használom az ABP-vel:
-Adblock Warning Removal List 
-Adware filters
-EasyList
-EasyPrivacy+EasyList
-Fanboy's Annoyance List
-Fanboy's Social Blocking List
-ABP filters
-hufilter
-I don't care about cookies
-Malware Domains
-Spam404

**Comment by szpeter80** [comment]
A hibát sajnos nem sikerült reprodukálni. Arra tudok gondolni hogy a FF több szálon indul, és a session restore miatt egyből betölti a YT-t ami még az ABP előtt lejön és bedobja a reklámot. Ez megmagyarázná hogy refresh-re miért javul meg. A másik tippem h a Google A/B teszteli a reklámkikerülést, és egyelőre nagyon kis számban megy a teszt hogy nehogy feltűnjön, de ez nem magyarázná meg hogy miért csak induláskor történik (persze nézhetik a referert vagy bármilyen más metrikát amijük van, és hát elég sok van). Valószínű nem szűrőfájl probléma, mert a szűrők statikusak, vagyis nem változtatják a viselkedésüket frissítések között (kivéve ha új verziót tölt le az ABP, persze).

**Comment by Rencer** [comment]
Szóval, ha vagy a FF -vagy modhatnánk hogy a Chrome (hiszen manapság minden létező böngésző Chrome-alapú)- tehát végső soron akkor megint a Google (önmagukat nem meghazudtolóan) szúrja el szándékosan azt, ami eredetileg jól és egyszerűen működött, akkor csupán azt remélhetjük, hogy az ABP fejlesztői majd remélhetőleg megoldják hogy ne kelljen az idegesítő, ránk erőltetett reklámáradatot lesnünk...
Amúgy érdekes hogy nem tudod reprodukálni; én most kipróbáltam több alkalommal egymás után, és ha YT oldallal indítom újra a FF-et most mindíg ott vannak a reklámok. Ha újratöltöm az oldalt akkor eltünnek. Bár az is igaz most az FF a létező legjobban elcseszte a dolgokat; hiszen most kb. minden kiegészítőt alapból letilt. Én is a netes fórumokon talált (Linuxos rendszerre való) trükköket használom, hogy amíg ez a hülyeség a kiegészítőkkel kapcsolatban ki nem lesz javítva, legalább betöltse őket.
Bár ennek van egy nagy hátránya (lehet ez amúgy Linux specifikus) hogy a FF megállás nélkül létrehoz és azonnal töröl egy fáljt, gyakorlatilag non-stop cseszteti a vinyót. Jobbnak látom inkább egyáltalán nem használni, mert evvel csak a drága vinyót teszi tönkre.
